AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM template - create a serverless website for covid cases history
Parameters:
  SlackWebhookURL:
    Type: String
    Description: Slack webhook url for sending notifications
  ArtefactsS3Bucket:
    Type: String
    Description: S3 Bucket for artefacts
  ArtefactsS3KeyPrefix:
    Type: String
    Description: Prefix for the objects in the ArtefactsS3Bucket
  WebsiteS3Bucket:
    Type: String
    Description: S3 Bucket that will store the html files for the website
Resources:
  COVIDCasesHistoryWebsiteFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: This function monitors the NSW Health website for COVID case numbers and creates a website showing the numbers.
      Handler: src/covid_cases_history_website.lambda_handler
      Runtime: python3.7
      MemorySize: 256
      Timeout: 300
      Events:
        CWEventsSchedule:
          Type: Schedule
          Properties:
            Schedule: "cron(0/5 * * * ? *)"
            Name: CheckExternalWebsiteForCOVIDCasesUpdates
            Description: Check external websites for COVID cases updates
            Enabled: True
      Policies:
      - AWSLambdaBasicExecutionRole
      - S3ReadPolicy:
          BucketName: !Ref ArtefactsS3Bucket
      - S3WritePolicy:
          BucketName: !Ref ArtefactsS3Bucket
      - S3ReadPolicy:
          BucketName: !Ref WebsiteS3Bucket
      - S3WritePolicy:
          BucketName: !Ref WebsiteS3Bucket
      Environment:
        Variables:
          SLACK_WEBHOOK_URL: !Ref SlackWebhookURL
          ARTEFACTS_S3_BUCKET: !Ref ArtefactsS3Bucket
          ARTEFACTS_S3_KEY_PREFIX: !Ref ArtefactsS3KeyPrefix
          WEBSITE_S3_BUCKET: !Ref WebsiteS3Bucket
      
